### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by nimaam** [hangon1234/laravel-jitsi-jwt#1]
Dear Friend 
I followed the steps for installation but it has problem for https://domain/login and report the login not found.
Could you please help me.
With Best Regards.
Nima

**Comment by hangon1234** [comment]
> Dear Friend
> I followed the steps for installation but it has problem for https://domain/login and report the login not found.
> Could you please help me.
> With Best Regards.
> Nima

@nimaam try to run this command
php artisan serve
I think it should work. (It seems you already have php and composer)
If it works without problem, maybe you can configure web server
I am not really good at configuring server. What if you use docker? Laradock works without any problem.

**Comment by hangon1234** [comment]
no any further comment, close.
