### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by itsmeduard** [hangon1234/laravel-jitsi-jwt#2]
*You should have running instance of Jitsi and configure it uses JWT token authentication.
* set URL of your jitsi instance, and JWT token secret key.

How to do that?

**Comment by itsmeduard** [comment]
*You should have running instance of Jitsi and configure it uses JWT token authentication.
* set URL of your jitsi instance, and JWT token secret key.

How to do that?

**Comment by hangon1234** [comment]
@itsmeduard 
Hello, please look into https://github.com/jitsi/docker-jitsi-meet
If you know a bit about Docker, follow their guide and you can easily setup fresh jitsi instance.
Please also look info about JWT token https://tools.ietf.org/html/rfc7519
For only testing just put some test only url if you verify your installation. (for example, put https://test-my-jitsi.com)
This will not work , but you will see the app will create token and try to redirect you.
